plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
remote_theme: pages-themes/cayman@v0.2.0
title: TypeScript Reference for JS developers
markdown: GFM
description: Glossary of keywords, operators, statements and directives 
include:
  - README.md