plugins:
  - jekyll-relative-links
  - jekyll-remote-theme  
remote_theme: just-the-docs/just-the-docs
relative_links:
  enabled: true
  collections: true
title: TypeScript Reference for JS developers
markdown: GFM
description: Glossary of keywords, operators, statements and directives 
include:
  - README.md